### ISSUE TITLE
Windows: Some build steps fail with "The command line is too long"

### ISSUE THREAD

**Issue by cwillisf** [LLK/scratch-blocks#2080]
### Expected Behavior

Building scratch-blocks on Windows should succeed.

Excerpt from expected output (taken from a Linux build):

```
Using local compiler: google-closure-compiler ...

SUCCESS: blockly_compressed_vertical.js
Size changed from 3124 KB to 956 KB (31%).
SUCCESS: blockly_uncompressed_vertical.js
SUCCESS: blockly_uncompressed_horizontal.js
SUCCESS: blockly_compressed_horizontal.js
Size changed from 3094 KB to 945 KB (31%).
SUCCESS: blocks_compressed_horizontal.js
Size changed from 39 KB to 19 KB (49%).
blocks_vertical/vertical_extensions.js:54: WARNING - Misplaced function annotation. This JSDoc is not attached to a function node. Are you missing parentheses?
  return function() {
  ^^^^^^^^^^^^^^^^^^^

0 error(s), 1 warning(s)
SUCCESS: blocks_compressed_vertical.js
Size changed from 179 KB to 90 KB (50%).
SUCCESS: blocks_compressed.js
Size changed from 22 KB to 8 KB (37%).
```

### Actual Behavior

The output of `npm i` (which internally runs `python build.py` among other steps) includes the message "The command line is too long" more than once. There are at least two problems here:

- Some invocations of `google-closure-compiler.cmd` fail because the command line is too long
- The overall build process reports success despite the failed invocations of the compiler

Excerpt from the output (note the absence of "SUCCESS" lines for `blockly_compressed_vertical.js` and `blockly_compressed_horizontal.js`):

```
Using local compiler: google-closure-compiler.cmd ...

The command line is too long.
UNKNOWN ERROR
The command line is too long.
UNKNOWN ERROR
SUCCESS: blockly_uncompressed_horizontal.js
SUCCESS: blockly_uncompressed_vertical.js
SUCCESS: blocks_compressed_horizontal.js
Size changed from 39 KB to 19 KB (49%).
blocks_vertical/vertical_extensions.js:54: WARNING - Misplaced function annotation. This JSDoc is not attached to a function node. Are you missing parentheses?
  return function() {
  ^^^^^^^^^^^^^^^^^^^

0 error(s), 1 warning(s)
SUCCESS: blocks_compressed_vertical.js
Size changed from 183 KB to 90 KB (49%).
SUCCESS: blocks_compressed.js
Size changed from 22 KB to 8 KB (37%).
```

### Steps to Reproduce

1. On Windows, open a command prompt or PowerShell
   - To reproduce this issue, do not use Cygwin, MinGW, Git Bash, WSL, etc.
2. Clone the scratch-blocks repository
3. In the scratch-blocks directory, run `npm i`

### Operating System and Browser

Windows 10 (probably any version of Windows capable of running `npm`)

**Comment by cwillisf** [comment]
We should fix this, but in the mean time I recommend using Cygwin or WSL to work on scratch-blocks in Windows. WSL is more reliable and is the way I do most of my work these days.

WSL setup instructions (requires Windows 10): https://docs.microsoft.com/en-us/windows/wsl/install-win10
Cygwin setup instructions: https://cygwin.com/install.html

Note that you'll need to install Python "inside" of WSL or Cygwin for this to be a complete & reliable solution. Once you have everything installed, the regular `npm i` should work from the WSL or Cygwin prompt.

**Comment by apple502j** [comment]
This may be due to "unnecessary" use of absolute paths in the code, although I'm not sure...

**Comment by Salik-Rafiq** [comment]
Did try the PowerShell "fix" but it doesn't fix the problem for me. It would always choose to do the remote compile - which mostly works  - it's kinda hit and miss.

There is a ps1 (powershell) file but that doesn't also seem to work for me.

I guess WSL is the only way to run this process for now.

**Comment by hun9k** [comment]
Problems also occur on Git Bash.

**Comment by PhidgetsInc** [comment]
Using Windows 10, I was able to fix this by writing out the required filenames to a file and then using the hidden option --flagfile in build.py to feed in that file. See [https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/CommandLineRunner.java#L695](https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/CommandLineRunner.java#L695). No clue why it's a hidden option! Found that tidbit on some stackoverflow answer.

The following was done in both `def gen_blocks` and `def gen_core` in build.py, instead of line `params.append(("js_file", filename))`:

`f = open("gen_reqfiles.txt", "w")`
`for filename in filenames:`
`      # Append filenames as false arguments the step before compiling will`
`      # either transform them into arguments for local or remote compilation`
`      # params.append(("js_file", filename))`
`      f.write(filename + " ")`
`    f.close()`
`    params.append(("flagfile", "gen_reqfiles.txt"))`

(The code tag is not preserving the required Python indentation)

It was still throwing "UNKNOWN ERROR" when generating the blockly_compressed_horizontal and vertical, so I commented out line 446: `#if original_b > 0 and compressed_b > 0:` so that it would actually write out the file.  OriginalSize was returning 0 bytes everytime, and compressed was returning ~954KB.

**Comment by NikTheGeek1** [comment]
> 

Would using a docker container work in this case? I am getting the same error when I try to `npm run prepublish`  using an Ubuntu container on a Windows host machine. Has anyone tried making it work with Docker?

**Comment by PaxtonPenguin** [comment]
i'm getting the error, even on wsl

**Comment by PaxtonPenguin** [comment]
another fix, thanks to cst1229 for finding it, is [https://github.com/scratchfoundation/scratch-blocks/pull/2138](this)

**Comment by CST1229** [comment]
> another fix, thanks to cst1229 for finding it, is [https://github.com/scratchfoundation/scratch-blocks/pull/2138](this)

Thank the creator of the PR, not me.

**Comment by cwillisf** [comment]
scratch-blocks v2 is a complete rewrite built on top of upstream [Blockly](https://github.com/RaspberryPiFoundation/blockly/). The old build system (Google Closure compiler, `python build.py`, the `core/` and `shim/` directories, etc.) no longer exists. This issue is no longer applicable. Thank you for reporting it!

If you believe this issue is still relevant to scratch-blocks v2, please let us know and we can reopen it.
